$('.owl-carousel').owlCarousel({
    loop:true,
    margin:48,
    nav:true,
    dots:false,
    center:true,
    autoWidth:true,
    items:1,
    responsive:{
        0:{
            dots:true
        },
        1200:{
            dots:false
        },               
    }
});